name: Publish
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: trmcnvn/firefox-addon@v1
        with:
          uuid: '{e5c23d2e-17a8-4796-bb3f-9726db2d1012}'
          xpi: build/my-addon.xpi
          manifest: manifest.json
          api-key: ${{ secrets.FIREFOX_API_KEY }}
          api-secret: ${{ secrets.FIREFOX_API_SECRET }}
